name: Dev - New Sync Airflow DAG to S3
on:
  pull_request:
    branches:
      - Master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev-deploy:
    runs-on: windows-latest
    environment:
      name: Dev
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Zip Lambda Function
        run: .github\workflows\dag_build.ps1
        shell: powershell
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     audience: sts.amazonaws.com
      #     aws-region: ap-south-1
      #     role-to-assume: arn:aws:iam::160885270668:role/demo_role
      - name: prit temp file list
        run: |
          cd ./temp/dna-datalake-airflow/config
          ls 
          echo "======================================="
          cd ../../..
          cd ./temp/dna-datalake-airflow/DAG
          ls 
      - name: Upload DAG to S3
        run: |
          cat ./temp/dna-datalake-airflow/config/requirements_2.7.2.txt
      # - name: Upload DAG to S3
      #   run: |
      #     aws s3 cp ./temp s3://test-github-actionbucket/ --recursive
