name: Dev - New Sync Airflow DAG to S3
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev-deploy:
    runs-on: windows-latest
    environment:
      name: Dev
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Zip Lambda Function
        run: .github\workflows\dag_build.ps1
        shell: powershell
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     audience: sts.amazonaws.com
      #     aws-region: us-east-1
      #     role-to-assume: arn:aws:iam::763084030621:role/admin/github-actions-enterprise-data-role
      - name: Upload DAG to S3
        run: |
          aws s3 cp ./temp s3://datalake-jobs-code-dev-us-east-1-763084030621-invh/ --recursive